#!/bin/bash

#Note!  If on mac, will have to do "brew install coreutils" (this may itself require installing brew).  

PWD1=`pwd`
PWD2=$1

domain=`uname -a | awk '{print $1}'`
if [ -e $PWD1/$PWD2 ] 
then
  blah=$PWD1/$PWD2
  if [ "$domain" == "Darwin" ]
  then
    echo `greadlink -f $blah`
  else
    echo `readlink -f $blah`
  fi
else
  if [ -e $PWD2 ]
  then 
    if [ "$domain" == "Darwin" ]
    then
      echo `greadlink -f $PWD2`
    else
      echo `readlink -f $PWD2`
    fi
  else
    echo "$PWD1/$PWD2 does not exist." 
  fi
fi
