#!/bin/bash

HOST='bostonfusion.com'
USER='alexgeorge@bostonfusion.com'
PASSWD=`cat ~/.passwd/ftp_pw`

#Cut up username
theuser=`echo $USER | tr '@' ' ' | awk '{print $1}'`

# Initialize our own variables:
delete=false
verbose=0
keep=false
deleteall=false

while getopts "hdD" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    d)  delete=true
        ;;
    D)  deleteall=true
        ;;
    k)  keep=true
        ;;
    esac
done

shift $((OPTIND-1))

#Safety Check
if [[ $deleteall == true ]]
then
  read -p "This will delete ALL web files not in the keep directory.  Are you sure? (y/n)" -n 1 -r
  echo    
  if  [[ $REPLY =~ ^[Yy]$ ]]
  then
    :
  else 
    echo "exiting, you coward."
    exit 1 
  fi
fi

#Do it
if [[ $deleteall == true ]]
then
ftp -p -n -v $HOST << EOT
ascii
user $USER $PASSWD
prompt
mdelete *
bye
EOT
elif [[ $delete == true ]] && [[ $keep == false ]]
then
ftp -p -n -v $HOST << EOT
ascii
user $USER $PASSWD
delete "$1"
bye
EOT
elif [[ $delete == false ]] && [[ $keep == false ]]
then
ftp -p -n -v $HOST << EOT
ascii
user $USER $PASSWD
put "$1"
bye
EOT
echo ""
echo "Posted at http://www.bostonfusion.com/$theuser/$1"
elif [[ $delete == true ]] && [[ $keep == true ]]
then
ftp -p -n -v $HOST << EOT
ascii
user $USER $PASSWD
cd keep
delete "$1"
bye
EOT
elif [[ $delete == false ]] && [[ $keep == false ]]
then
ftp -p -n -v $HOST << EOT
ascii
user $USER $PASSWD
cd delete
put "$1"
bye
EOT
fi
