#!/bin/bash

tocopy=""

if [ "$1" == "-d" ]
then
  #Workflow for directory
 if [ -e web_temp_ag_this_is_a_unique_name ] 
 then
   rm -r web_temp_ag_this_is_a_unique_name
 fi
  mkdir web_temp_ag_this_is_a_unique_name
  mkdir web_temp_ag_this_is_a_unique_name/$2
  for input in "${@:3}"
  do
    raw=${input%.*}
    ext=${input#*.}
    if [ "$input" == "web_temp_ag_this_is_a_unique_name" ] 
    then 
      continue 
    fi
    if [ "$ext" == "sh" ]
    then
      cp $input web_temp_ag_this_is_a_unique_name/$2/$raw.txt
    else
      cp $input web_temp_ag_this_is_a_unique_name/$2/$input
    fi
  done
  scp -r web_temp_ag_this_is_a_unique_name/$2 cag@klong.physics.ucsb.edu:/www/htdocs/people/cag
  rm -r web_temp_ag_this_is_a_unique_name
  echo "Posted line at http://hep.ucsb.edu/people/cag/$2"
else
  #Regular Workflow
  for input in "$@"
  do
    raw=${input%.*}
    ext=${input#*.}
    if [ "$ext" == "sh" ]
    then
      tocopy="$tocopy $raw.txt"
      echo "Posted online at http://hep.ucsb.edu/people/cag/$raw.txt"
    else
      tocopy="$tocopy $input"
      echo "Posted online at http://hep.ucsb.edu/people/cag/$input"
    fi
  done
  scp $tocopy cag@klong.physics.ucsb.edu:/www/htdocs/people/cag/
fi
